on: [push]
name: CI-test

env:
  #      VERSION=$(echo ${TRAVIS_BRANCH} | sed 's/release-//')
  VERSION: 2.20.0
  PYTHON_ARTIFACTS_DIR: python
  STAGING: https://dist.apache.org/repos/dist/dev/beam/${VERSION}/${PYTHON_ARTIFACTS_DIR}
  ZIP_FILE: apache-beam-${VERSION}.zip

jobs:

  get_source:
    runs-on: ubuntu-18.04
    steps:
    - name: Download source
      run: wget ${{ env.STAGING }}/${{ env.ZIP_FILE }}
    - name: Unzip source
      run: unzip ${{ env.ZIP_FILE }}
    - name: Upload source
      uses: actions/upload-artifact@v2
      with:
        name: source
        path: apache-beam-${{ env.VERSION }}

  build_wheels:
    name: Build wheel on ${{ matrix.os }}
    needs: get_source
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, macos-latest]
    steps:
    - name: Download source
      uses: actions/download-artifact@v2
      with:
        name: source
        path: apache-beam-${{ env.VERSION }}
    - name: Install Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.7'
    - name: Install cibuildwheel
      run: python3 -m pip install cibuildwheel==1.4.2
    - name: Build wheel
      working-directory: apache-beam-${{ env.VERSION }}
      env:
        CIBW_BUILD: cp27-* cp37-*
        CIBW_BUILD_VERBOSITY: 1
      run: cibuildwheel --output-dir wheelhouse
      shell: bash
    - name: Upload wheels
      uses: actions/upload-artifact@v2
      with:
        name: wheelhouse-${{ matrix.os }}
        path: apache-beam-${{ env.VERSION }}/wheelhouse/

  upload_to_gcp:
    name: Upload wheels to GCS bucket
    needs: build_wheels
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        os: [ubuntu-18.04, macos-latest]
    steps:
    - name: Download wheels
      uses: actions/download-artifact@v2
      with:
        name: wheelhouse-${{ matrix.os }}
        path: wheelhouse/
    - name: Authenticate on GCP
      uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        service_account_email: ${{ secrets.CCP_SA_EMAIL }}
        service_account_key: ${{ secrets.CCP_SA_KEY }}
    - name: Copy wheels to GCS bucket
      run: gsutil cp -r -a public-read wheelhouse/* gs://${{ secrets.CCP_BUCKET }}/${GITHUB_REF##*/}/
